name: Deploy Vite app to Github Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up runtime
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }

      # Install dependencies
      - name: Install deps
        uses: npm i

      # Build the app
      - name: Build app
        uses: npm run build

      # Deploy to github pages
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
